---
name: ecr

permissions:
  id-token: write

on:
  workflow_dispatch:

  push:
    branches:
      - main

  schedule:
    - cron: 0 0 * * 0 # sunday midnight

jobs:
  ecr-private:
    uses: andreswebs/gh-actions/.github/workflows/aws-ecr-push-image.yml@main
    with:
      runs-on: ubuntu-latest
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      ecr-repo-name: andreswebs/header-authorizer-lambda
      context-dir: .

  update-dev:
    needs: ecr-private
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Get image URI
        id: image-uri
        uses: andreswebs/gh-actions/.github/actions/artifact-as-value@main
        with:
          key: image

      - name: Update config parameter
        uses: andreswebs/gh-actions/.github/actions/aws-ssm-put-param@main
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
          parameter_type: String
          parameter_name: /images/dev/header-authorizer-lambda
          parameter_value: ${{ steps.image-uri.outputs.value }}
